# Generated by Django 4.0.4 on 2022-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weBankAPI', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
