# Generated by Django 4.0.4 on 2022-04-27 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weBankAPI', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
