# Generated by Django 4.0.4 on 2022-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weBankAPI', '0006_accounts_fullname_alter_accounts_account_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='accounts',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
